### ISSUE TITLE
Beispielcode für die Bibliothek

### ISSUE THREAD

**Issue by IvanVilimonovic** [ProPra16/programmierpraktikum-abschlussprojekt-ji#3]
Hallo Yasin,

kannst du uns eventuell doch ein Beispiel geben, wie wir beispielsweise einen Code der in Form eines Strings vorliegt, mit der Bibliothek kompilieren? Wir haben es versucht, anhand einer Klasse zu testen (siehe unten), kommen aber leider nicht weiter. Ich bedanke mich im Voraus!

Viele Grüße
Ivan

```
package TestPackage;
import vk.core.api.*;
public class Main {

    public static void main(String[] args) {

        String s = "public class CTest { public void someMethod(){} }";

        CompilationUnit cu = new CompilationUnit("CTest", s, false);
        JavaStringCompiler jsc = CompilerFactory.getCompiler(cu);

        jsc.compileAndRunTests();
        jsc.getCompilerResult();
    }
}
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:75)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at vk.core.internal.InternalCompiler.runAllTests(InternalCompiler.java:99)
	at vk.core.internal.InternalCompiler.compileAndRunTests(InternalCompiler.java:65)
	at TestPackage.Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

Process finished with exit code 1
```

**Comment by yyazgan** [comment]
Ich habe es bei mir ausprobiert und es funktioniert fehlerfrei. Ich denke, dass ihr beim Einbinden etwas falsch gemacht habt.

Bitte den Parameter folgendermaßen setzen:
`CompilationUnit cu = new CompilationUnit("CTest", s, false);`

Dann kann man folgendermaßen auf der Konsole testen, ob es fehlerfrei kompiliert:
`System.out.println(jsc.getCompilerResult().hasCompileErrors());`
